import type { Metadata } from "next";
import { Geist, Geist_Mono, Lobster, Poppins } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/tanstackProvider";
import { Footer } from "@/components/shared/footer";
import Navbar from "@/components/shared/Navbar";
import { Toaster } from "sonner";
import ReduxProvider from "./providers/redux-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const lobster = Lobster({
  variable: "--font-lobster",
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create seagoville",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${lobster.variable} ${geistSans.variable} ${geistMono.variable} font-sans  antialiased`}
      >
        <TanstackProvider>
          <ReduxProvider>
            <Navbar />
            {children}
            <Toaster
              position="top-center"
              richColors
              closeButton
              duration={4000}
              visibleToasts={3}
              offset={16}
            />

            <Footer />
          </ReduxProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
